version: '3'

services:
  backend-to-api:
    image: wizerd/pandora-to-api:latest
    restart: always
    ports:
      - "50011:33333"
    environment:
      - BASE_URL=<Pandora-Next的部署地址，如：https://pandoranext.com>
      - PROXY_API_PREFIX=<Pandora-Next的PROXY_API_PREFIX>
      - UPLOAD_BASE_URL=<50011端口在公网可以访问到的地址，如：http://1.2.3.4:50011，如果使用了反代需填入反代后的域名如：https://pandora-backend-api.com>
      - KEY_FOR_GPTS_INFO=<一个仅用于获取GPTs信息的fk> # 如果不需要额外使用gpts，可以不填
      - GPT_4_S_New_Name=gpt-4-s # gpt-4-s模型的自定义模型名称，支持同时设置多个，用英文逗号分隔
      - GPT_4_MOBILE_NEW_NAME=gpt-4-mobile # gpt-4-mobile模型的自定义模型名称，支持同时设置多个，用英文逗号分隔
      - GPT_3_5_NEW_NAME=gpt-3.5-turbo # gpt-3.5-turbo模型的自定义模型名称，支持同时设置多个，用英文逗号分隔
      - API_PREFIX=<本项目接口前缀> # 本项目/v1接口的前缀，示例：666，如果留空默认为原版本一致
      - LOG_LEVEL=<日志等级> # 日志输出等级，可选值：DEBUG,INFO,WARNING,ERROR,CRITICAL
      - NEED_LOG_TO_FILE=<是否需要输出日志到文件> # 是否需要输出日志到文件，可选值：true,false
    volumes:
      - ./log:/app/log
      - ./images:/app/images
      - ./gpts.json:/app/gpts.json
    
  redis:
  image: "redis:alpine"
  command: redis-server --appendonly yes
  ports:
    - "46379:6379"
  volumes:
    - ./redis-data:/data