version: '3'

services:
  backend-to-api:
    image: wizerd/pandora-to-api:latest
    restart: always
    ports:
      - "50011:33333"
    environment:
      - BASE_URL=<Pandora-Next的部署地址，如：https://pandoranext.com>
      - PROXY_API_PREFIX=<Pandora-Next的PROXY_API_PREFIX>
      - UPLOAD_BASE_URL=<50011端口在公网可以访问到的地址，如：http://1.2.3.4:50011，如果使用了反代需填入反代后的域名如：https://pandora-backend-api.com>
      - KEY_FOR_GPTS_INFO=<一个仅用于获取GPTs信息的fk> # 如果不需要额外使用gpts，可以不填
    volumes:
      - ./log:/app/log
      - ./images:/app/images
      - ./gpts.json:/app/gpts.json
    