name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract tag name
      id: tag_name
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

    - name: Build and push Docker image with Release tag
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          wizerd/pandora-to-api:${{ steps.tag_name.outputs.tag }}
          wizerd/pandora-to-api:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
